### ISSUE TITLE
How to infer?

### ISSUE THREAD

**Issue by gheyret** [sh951011/Naver-AI-Hackathon-2019-Speech-Team_Kai.Lib#1]
how to get text from a short audio file? 
your infer code did not work?

**Comment by sooftware** [comment]
Do you mean a short audio file, a word audio file?

**Comment by gheyret** [comment]
Yes.

**Comment by sooftware** [comment]
It will also work in word units because it determines phonemes in 21 ms increments. However, if it's a word unit, you can use the CNN model instead of this one.

**Comment by sooftware** [comment]
and Further modifications are in progress in another repository.
link : https://github.com/sh951011/Korean-ASR
I haven't tested it but I think it will perform better than the current repository model

**Comment by gheyret** [comment]
Thanks.
